source 'https://rubygems.org'
gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
gem 'haml', '~> 4.0', '>= 4.0.7'
gem 'better_errors', '~> 2.1', '>= 2.1.1'
gem 'puma', '~> 2.15', '>= 2.15.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise', '~> 3.5', '>= 3.5.2'
gem 'turbolinks', '~> 2.5', '>= 2.5.3'
gem 'jquery-rails'
gem 'simple_form', '~> 3.2'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
